import { IProductRepository } from '../../domain/repositories/product.repository.interface';
import { ProductEntity } from '../../domain/entities/product.entity';

interface CreateProductInput {
  categoryId: string;
  name: string;
  slug: string;
  description?: string;
  sku: string;
  costPrice: number;
  sellingPrice: number;
  weight?: string;
  ingredients?: string;
  allergens?: string;
  expiryDays?: number;
  storageTemp?: string;
  isCombo?: boolean;
  comboPrice?: number;
  isSeasonal?: boolean;
  seasonalStart?: Date;
  seasonalEnd?: Date;
  isActive?: boolean;
  images?: { url: string; isPrimary: boolean; sortOrder: number }[];
  comboItems?: { productId: string; quantity: number }[];
}

export class CreateProductUseCase {
  constructor(private readonly productRepo: IProductRepository) {}

  async execute(input: CreateProductInput): Promise<ProductEntity> {
    // Check if slug exists
    const existing = await this.productRepo.findBySlug(input.slug);
    if (existing) {
      throw new Error(`Product with slug ${input.slug} already exists`);
    }

    return this.productRepo.create({
      categoryId: input.categoryId,
      name: input.name,
      slug: input.slug,
      description: input.description || null,
      sku: input.sku,
      costPrice: input.costPrice,
      sellingPrice: input.sellingPrice,
      weight: input.weight || null,
      ingredients: input.ingredients || null,
      allergens: input.allergens || null,
      expiryDays: input.expiryDays || null,
      storageTemp: input.storageTemp || null,
      isCombo: input.isCombo ?? false,
      comboPrice: input.comboPrice || null,
      isSeasonal: input.isSeasonal ?? false,
      seasonalStart: input.seasonalStart || null,
      seasonalEnd: input.seasonalEnd || null,
      isActive: input.isActive ?? true,
      images: input.images?.map((img) => ({
        id: '', // Will be generated by DB
        url: img.url,
        isPrimary: img.isPrimary,
        sortOrder: img.sortOrder,
      })) || [],
      comboItems: input.comboItems || [],
    });
  }
}
